import numpy as np
from ctypes import *

t = datetime.datetime(2013,6,14,13,59,56)

nside = 512
npix = hp.nside2npix(nside)



fun = CDLL('./gsm.so')

#fun.temperature_.argtypes = [POINTER(c_double), POINTER(c_float)]
#fun.temperature_.restype = c_double, c_float

nu_0 = np.arange(50,91, dtype=c_double) #the range of frequencies(MHz) from the mesurement
#nu = nu_0.ctypes.data_as(POINTER(c_double * np.size(nu_0)))

#nu = c_double(65.0)

tem = np.zeros(npix, dtype=c_float) #temperature array generated by gsm.f90
t = tem.ctypes.data_as(POINTER(c_float))

T_nu = np.zeros(nu_0.size)
vals=[]
freq = nu_0.size

for i in range(freq):
    nu = nu_0[i:].ctypes.data_as(POINTER(c_double * np.size(nu_0)))
    fun.temperature_(nu, t)

np.savetxt('temperatures.dat',tem)
